var mongoose=require("mongoose");
var schema=new mongoose.Schema({
    identifiantProjet:{
        type:mongoose.Types.ObjectId,
        required:true
    },
    nom:{
        type:String,
        required:true
    },
    adresse:{
        type:String,
        required:true
    },
    genre:{
        type:String,
        required:true
    },
    age:{
        type:String,
        required:true
    },
    profession:{
        type:String,
        required:true
    },
    status:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    objectifs:{
        type:String,
        required:true
    },
    environnement:{
        type:String,
        required:true
    },
    photo:{
        type:String,
        required:true
    }
});
var persona=mongoose.model("personas",schema);
module.exports=persona;